# Ocal Browser - Microsoft Store Package Build Script
# Builds an AppX / MSIX package ready for Microsoft Partner Center or local sideloading test.

$ErrorActionPreference = "Stop"

$version = (Get-Content package.json | ConvertFrom-Json).version
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   🌌 Ocal Browser v$version - Microsoft Store Build       " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Check Store Assets
Write-Host "[1/4] Checking Microsoft Store visual assets..." -ForegroundColor Yellow
if (-not (Test-Path "build\appx\StoreLogo.png")) {
    Write-Host "Generating AppX visual assets..." -ForegroundColor Gray
    python scripts/generate-store-assets.py
}
Write-Host "Store visual assets verified in build\appx\" -ForegroundColor Green

# 2. Cleanup Store Output Directory
Write-Host "[2/4] Preparing output directory: dist-store..." -ForegroundColor Yellow
if (Test-Path "dist-store") {
    try {
        Remove-Item -Recurse -Force "dist-store"
    } catch {
        Write-Host "Notice: Some files in dist-store were locked, continuing..." -ForegroundColor Gray
    }
}
New-Item -ItemType Directory -Path "dist-store" -Force | Out-Null

# 3. Compile AppX / MSIX Package
Write-Host "[3/4] Packaging Electron application into AppX / MSIX..." -ForegroundColor Magenta
Write-Host "Executing electron-builder --win appx..." -ForegroundColor Gray

# Build AppX package
cmd.exe /c npx electron-builder --win appx --config.directories.output=dist-store
if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "Note: If electron-builder asks for a valid code signing cert for local testing," -ForegroundColor Yellow
    Write-Host "you can upload the unsigned/partner-center package directly to Partner Center," -ForegroundColor Yellow
    Write-Host "as Microsoft signs the package automatically during store ingestion!" -ForegroundColor Yellow
    throw "Electron AppX packaging failed with exit code $LASTEXITCODE."
}

# 4. Summary & Instructions
Write-Host ""
Write-Host "[4/4] Microsoft Store Build Finished!" -ForegroundColor Green
Write-Host "==========================================================" -ForegroundColor Cyan

$appxFiles = Get-ChildItem "dist-store\*.appx", "dist-store\*.msix", "dist-store\*.appxupload", "dist-store\*.msixupload" -ErrorAction SilentlyContinue

if ($appxFiles) {
    foreach ($file in $appxFiles) {
        Write-Host "Package created: $($file.FullName) ($([math]::Round($file.Length / 1MB, 2)) MB)" -ForegroundColor White
    }
} else {
    Write-Host "Files generated in dist-store:" -ForegroundColor White
    Get-ChildItem "dist-store" | Select-Object Name, Length | Format-Table
}

Write-Host ""
Write-Host "=== HOW TO PUBLISH TO MICROSOFT STORE ===" -ForegroundColor Cyan
Write-Host "1. Register an account at: https://partner.microsoft.com/dashboard" -ForegroundColor White
Write-Host "2. Reserve your app name ('Ocal Browser') in Apps and Games > Product management" -ForegroundColor White
Write-Host "3. In 'Product Identity', copy:" -ForegroundColor White
Write-Host "   - Package/Identity/Name       -> put in package.json > build > appx > identityName" -ForegroundColor Gray
Write-Host "   - Package/Identity/Publisher  -> put in package.json > build > appx > publisher" -ForegroundColor Gray
Write-Host "   - Publisher Display Name      -> put in package.json > build > appx > publisherDisplayName" -ForegroundColor Gray
Write-Host "4. Re-run 'npm run build-store' to generate your final store package." -ForegroundColor White
Write-Host "5. Upload the generated .appx / .msix to 'Packages' section in Partner Center." -ForegroundColor White
Write-Host ""
Write-Host "ALTERNATIVE (EASIEST): Win32 Direct Installer Submission" -ForegroundColor Yellow
Write-Host "Microsoft Store now directly accepts Win32 .exe installers!" -ForegroundColor White
Write-Host "You can submit your standard installer generated by 'npm run build-inno' with:" -ForegroundColor White
Write-Host "   Silent install arguments: /VERYSILENT /NORESTART" -ForegroundColor Gray
Write-Host "==========================================================" -ForegroundColor Cyan
